shared:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  email: <%= ENV["EMAIL"] %>
  sendgrid:
    address: <%= ENV["SENDGRID_ADDRESS"] %>
    username: <%= ENV["SENDGRID_USERNAME"] %>
    password: <%= ENV["SENDGRID_PASSWORD"] %>
    port: <%= ENV["SENDGRID_PORT"] %>
